name: asdf-java Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/get-package@v1
      with:
        brew: coreutils jq shellcheck
        apt-get: jq shellcheck
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck ./bin/functions
    - name: Install asdf
      uses: actions/checkout@v2
      with:
        repository: asdf-vm/asdf
        path: asdf
    - name: Run tests
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        which curl
        curl --version
        asdf plugin-test java "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version azul-zulu-8.44.0.11-jdk8.0.242
